workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120

    scripts:
      - name: Get Flutter packages
        script: | 
          flutter packages pub get
      - name: Install pods
        script: | 
          find . -name "Podfile" -execdir pod install \;
 
      - name: Flutter build ipa
        script: | 
          flutter build ipa --debug --no-codesign


    artifacts:
      - build/ios/ipa/*.ipa

