name: motors_app
description: Motors App by Stylemix

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

#Version APP
version: 1.2.3+27

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  #utils
  path_provider: ^2.0.15
  flutter_bloc: ^8.1.3
  image_picker: ^1.0.2
  flutter_html: ^3.0.0-beta.2
  mime: ^1.0.4
  quiver: ^3.2.1
  logger: ^2.0.2+1
  json_annotation: ^4.8.0
  google_sign_in: ^6.1.6
  sign_in_with_apple: ^5.0.0
  device_preview: ^1.1.0
  

  #provider
  provider: ^6.0.5

  #local_storage
  shared_preferences: ^2.1.1

  #network
  dio: ^5.1.2
  http: ^1.1.0

  #location
  geolocator: ^10.1.0
  geocoding: ^2.0.5

  #ui
  cupertino_icons: ^1.0.5
  flutter_vector_icons: ^2.0.0
  font_awesome_flutter: ^10.4.0
  flutter_svg: ^2.0.6
  carousel_slider: ^4.2.1
  photo_view: ^0.14.0
  google_maps_flutter: ^2.2.7
  url_launcher: ^6.1.11
  fluttertoast: ^8.1.2
  cached_network_image: ^3.2.3
  flutter_staggered_grid_view: ^0.7.0
  multi_select_flutter: ^4.1.3
  syncfusion_flutter_sliders: ^23.1.36
  searchable_listview: ^2.4.0
  youtube_player_flutter: ^8.1.2
  animated_text_kit: ^4.2.2
  google_fonts: ^6.1.0
  firebase_storage: ^11.2.5
  timeago: ^3.5.0
  firebase_messaging: ^14.6.5
  flutter_local_notifications: ^15.1.0+1
  webview_flutter: ^4.2.2
  loading_animation_widget: ^1.2.0+4
  line_icons: ^2.0.3
  app_tracking_transparency: ^2.0.4
  string_similarity: ^2.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  firebase_auth: ^4.15.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.6

  json_serializable: ^6.6.1

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  firebase_core: ^2.14.0
  cloud_firestore: ^4.8.2
  intl: ^0.18.1
  hive_generator: ^2.0.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/Osmania.jpg"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: IconsMotors
      fonts:
        - asset: assets/icons/IconsMotors.ttf

    - family: SFProDisplay
      fonts:
        - asset: assets/fonts/SFProDisplay-Black.ttf
        - asset: assets/fonts/SFProDisplay-Bold.ttf
        - asset: assets/fonts/SFProDisplay-Light.ttf
        - asset: assets/fonts/SFProDisplay-Medium.ttf
        - asset: assets/fonts/SFProDisplay-Regular.ttf
        - asset: assets/fonts/SFProDisplay-Semibold.ttf
        - asset: assets/fonts/SFProDisplay-Thin.ttf

    - family: Caviar
      fonts:
        - asset: assets/fonts/Caviar.ttf
        

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
