// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZnazv4f9z_aXrh9n67cWThyYXuH2Otac',
    appId: '1:578352914357:android:b00cac5bfd69f4d3e8c3fc',
    messagingSenderId: '578352914357',
    projectId: 'osmania-9e58a',
    databaseURL: 'https://osmania-9e58a-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'osmania-9e58a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA286IUn6lu70V_LWe8xz_DE9Gw3k5bBPg',
    appId: '1:578352914357:ios:b206582dda01ae9ee8c3fc',
    messagingSenderId: '578352914357',
    projectId: 'osmania-9e58a',
    databaseURL: 'https://osmania-9e58a-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'osmania-9e58a.appspot.com',
    androidClientId: '578352914357-15otrib2urkhl1qlf14dsm7uui8h42b0.apps.googleusercontent.com',
    iosClientId: '578352914357-mqhbdiirtdcq049327r2m4qdh535jc3j.apps.googleusercontent.com',
    iosBundleId: 'ufa.stylemixthemes.motors',
  );
}
